version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartparking
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  adminer:
    image: adminer
    ports: ["8080:8080"]

  mosquitto:
    image: eclipse-mosquitto:2
    ports: ["1883:1883", "9001:9001"]
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  pgdata:
