-- CreateTable
CREATE TABLE "public"."ParkingConfig" (
    "id" TEXT NOT NULL,
    "entranceLat" DOUBLE PRECISION NOT NULL DEFAULT 37.7749,
    "entranceLng" DOUBLE PRECISION NOT NULL DEFAULT -122.4194,
    "exitLat" DOUBLE PRECISION NOT NULL DEFAULT 37.7750,
    "exitLng" DOUBLE PRECISION NOT NULL DEFAULT -122.4195,
    "shopLat" DOUBLE PRECISION NOT NULL DEFAULT 37.7751,
    "shopLng" DOUBLE PRECISION NOT NULL DEFAULT -122.4196,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ParkingConfig_pkey" PRIMARY KEY ("id")
);
